### ISSUE TITLE
Actions with the same export name will be overwritten

### ISSUE THREAD

**Issue by lhz516** [mantrajs/mantra-core#10]
For example, I have a projects action in core module for following/commenting projects, I also have a projects action in admin module for adding/editing projects

However, if I export these actions with same name from two different modules, one of them will be overwritten. Probably the better way is to merge them, not to overwrite one of them.

If this is considered as a bug, I can submit a PR to fix it.

**Comment by HaareeKrishna** [comment]
@lhz516 Modules should be independent of each other so as action methods.

We need to have module namespacing for these methods while exporting them, so that we will eliminate overwriting existing action method from other module.
May be like this: 

`
import action from admin.js;
const admin = { action };
export default admin;
`

and access as 

`actions.admin.action, actions.project.action`

**Comment by lhz516** [comment]
@HaareeKrishna Okay, that makes sense. TY
